version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: predicting_at_risk_students
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=rootpassword mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: mudassirali89/studentinsight
    container_name: django_container
    restart: always
    command: python predicting_at_risk_students/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: predicting_at_risk_students
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
