# Generated by Django 3.2.25 on 2025-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='student_marks_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=300)),
                ('names', models.CharField(max_length=300)),
                ('sem1', models.CharField(max_length=300)),
                ('sem2', models.CharField(max_length=300)),
                ('sem3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='student_risk_prediction_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=300)),
                ('names', models.CharField(max_length=300)),
                ('sem1', models.CharField(max_length=300)),
                ('sem2', models.CharField(max_length=300)),
                ('sem3', models.CharField(max_length=300)),
                ('avg', models.CharField(max_length=300)),
                ('risk', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('marks', models.IntegerField()),
                ('risk_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
